### ISSUE TITLE
small version will be released soon? Did you do some experiments on it ? 

### ISSUE THREAD

**Issue by DuckJ** [iamhankai/ghostnet.pytorch#1]

**Comment by iamhankai** [comment]
What do you mean small version? < 100M Flops? We have experiments of GhostNet of 42MFLOPs in our paper:

![image](https://user-images.githubusercontent.com/9500784/70679701-e17c0c80-1cd0-11ea-8ead-55f72aaf35cd.png)

**Comment by DuckJ** [comment]
thank you. I see GhostNet 0.5x FLOPs is 42M.  what is the value of d and s set ?
I used the [https://github.com/Lyken17/pytorch-OpCounter](https://github.com/Lyken17/pytorch-OpCounter) to count the FLOPs, but seems different from yours.

**Comment by DuckJ** [comment]
small version, I mean the version that compared with mobilenet v3 small. 
Could you release the code of detection using the GhostNet for backbone

**Comment by iamhankai** [comment]
We set `d=3` and `s=2`. 

We used mmdetection for detection experiments. Just replacing the backbone with GhostNet is okay.

**Comment by iamhankai** [comment]
> thank you. I see GhostNet 0.5x FLOPs is 42M. what is the value of d and s set ?
> I used the https://github.com/Lyken17/pytorch-OpCounter to count the FLOPs, but seems different from yours.

The pytorch code is not fully verified. The tensorflow version shall prevail (https://github.com/iamhankai/ghostnet).

**Comment by DuckJ** [comment]
> We set `d=3` and `s=2`.
> 
> We used mmdetection for detection experiments. Just replacing the backbone with GhostNet is okay.

mmdetection ssd?

**Comment by iamhankai** [comment]
> thank you. I see GhostNet 0.5x FLOPs is 42M. what is the value of d and s set ?
> I used the https://github.com/Lyken17/pytorch-OpCounter to count the FLOPs, but seems different from yours.

I have a look at the code of https://github.com/Lyken17/pytorch-OpCounter. It counts the FLOPs of BN in a wrong way: https://github.com/Lyken17/pytorch-OpCounter/blob/84602bf2a3bd0ef2aefdd84649ef30027a8abee1/thop/count_hooks.py#L48. 

In addition, BN can be fused into Conv during inference so its FLOPs is 0.

**Comment by iamhankai** [comment]
> > We set `d=3` and `s=2`.
> > We used mmdetection for detection experiments. Just replacing the backbone with GhostNet is okay.
> 
> mmdetection ssd?

retinanet
