### ISSUE TITLE
Why are the k*k depthwise conv only used for downsample?

### ISSUE THREAD

**Issue by LightToYang** [iamhankai/ghostnet.pytorch#11]
MobileNetv3 applies `k*k` depthwise conv for each bottleneck, but GhostNet dose not. Dose the `d*d` cheap op work like `k*k` depthwise conv for extending receptive field?

**Comment by iamhankai** [comment]
You're right. `d*d` cheap op can not only generate ghost feature maps, but also extend receptive field that works like `k*k` depthwise conv in MobileNetV3 bottleneck.
