### ISSUE TITLE
关于cheap conv中relu的使用问题

### ISSUE THREAD

**Issue by pawopawo** [iamhankai/ghostnet.pytorch#12]
https://github.com/iamhankai/ghostnet.pytorch/blob/9aabd96d8132aa05f2a3e40a35f5b67c019494a2/ghost_net.py#L88
https://github.com/iamhankai/ghostnet.pytorch/blob/9aabd96d8132aa05f2a3e40a35f5b67c019494a2/ghost_net.py#L94
为什么上面两处一个relu=True，一个relu=False呢

**Comment by iamhankai** [comment]
Inspired by ShuffleNet: https://arxiv.org/abs/1707.01083

**Comment by deep-practice** [comment]
能提供预训练模型么？

**Comment by pawopawo** [comment]
> Inspired by ShuffleNet: https://arxiv.org/abs/1707.01083
![image](https://user-images.githubusercontent.com/38682321/76842281-f5f21700-6874-11ea-92a9-f7be26362536.png)

ShuffleNet中，concat或add后是有relu的

**Comment by iamhankai** [comment]
Thanks for your question. We remove the 2nd ReLU like ShuffleNet and remove the 3rd ReLU like MobileNetV2. The setting is more suitable for GhostNet.

**Comment by KnightWin123** [comment]
@pawopawo 你好 作者的tensorflow版本的代码是不是没有提供训练代码阿 这个怎么搞 刚刚入门求指教

**Comment by pawopawo** [comment]
> @pawopawo 你好 作者的tensorflow版本的代码是不是没有提供训练代码阿 这个怎么搞 刚刚入门求指教

我用的是pytorch训练，没用过tensorflow～

**Comment by pawopawo** [comment]
> Thanks for your question. We remove the 2nd ReLU like ShuffleNet and remove the 3rd ReLU like MobileNetV2. The setting is more suitable for GhostNet.

请问ghostnet 1.0的训练策略和ghostnet 1.3的训练策略一样么？
ghostnet1.0 可以复现出73.9，但是用相同的训练策略训练ghostnet 1.3，精度只有75.2。 论文中的ghostnet 1.3的精度是75.7

**Comment by KnightWin123** [comment]
> @pawopawo 你好 作者的tensorflow版本的代码是不是没有提供训练代码阿 这个怎么搞 刚刚入门求指教
> 
> 我用的是pytorch训练，没用过tensorflow～

那你的训练代码是自己写的吗..可以分享一下不

**Comment by DYJ1234567890** [comment]
> 能提供预训练模型么？

你好可以一起讨论一下这篇论文嘛

**Comment by tangshunpu** [comment]
![image](https://user-images.githubusercontent.com/39998326/77823671-cf1ac700-7137-11ea-970b-8888e0b8e12e.png)
