### ISSUE TITLE
关于论文中ResNet-56和Ghost-ResNet-56训练参数问题

### ISSUE THREAD

**Issue by breeze0** [iamhankai/ghostnet.pytorch#13]
大神你好，我在复现论文ResNet-56实验时遇到以下问题：我训练出resnet56的baseline精度比论文中的高不少，想请教下你的resnet56训练参数。还有Ghost-ResNet-56的训练参数也有baseline一样么？

**Comment by iamhankai** [comment]
你的训练参数是怎么样的？

**Comment by breeze0** [comment]
@iamhankai 我的训练参数采用的是你给的VGG训练建议 400epoch lr0.1 200，300，375epoch乘0.1，wd 1e-4，momentum 0.9，我用这个参数训练了两次resnet56，都稳定的到达了94.30。所以想请教下论文baseline为93.0的resnet56的训练参数以及ghost-resnet56的训练参数

**Comment by iamhankai** [comment]
Amazing! 我们可以用你说的超参训到更高的结果。
我们论文里为了公平对比，用的超参是resnet原论文里的策略：https://arxiv.org/pdf/1512.03385.pdf

**Comment by breeze0** [comment]
感谢你的回答，谢谢
