### ISSUE TITLE
cheap_operation

### ISSUE THREAD

**Issue by Abeni18** [iamhankai/ghostnet.pytorch#19]
Thank you for the implementation. I have some questions 
1. What is the difference between cheap_operation and depth_wise separable convolution 
2. I was expecting to see a linear transformation in the cheap_operation but it is an ordinary convolution
3. Where is the part that the cheap linear transformation implemented 

Thank you again

**Comment by iamhankai** [comment]
Cheap operation is a general concept. We implement cheap operation using depth_wise convolution for its simplicity.

**Comment by dronefreak** [comment]
Hi @iamhankai 

The cheap_operation in your PyTorch implementation does not seem to use depth_conv, while it does in the TF version. Please correct me if I am wrong.

**Comment by glenn-jocher** [comment]
Table 1. Comment says "In practice, the primary convolution in Ghost module here is pointwise convolution for its efficiency."
https://arxiv.org/pdf/1911.11907.pdf

So is each stride 1 Ghost module in Figure 1 basically 3 operations: a Conv2d() with a sequential depthwise seperable Conv2d() followed by a concat() of both Conv outputs?

<img width="500" alt="Screen Shot 2020-04-10 at 11 34 32 AM" src="https://user-images.githubusercontent.com/26833433/79014212-4597cb80-7b1f-11ea-9200-08bced2ec093.png">
