### ISSUE TITLE
About SELayer

### ISSUE THREAD

**Issue by WangDeyu** [iamhankai/ghostnet.pytorch#2]
After excitation layer, there is "clamp operation" but not "sigmoid", so why does it have this modification?

**Comment by iamhankai** [comment]
because clamp is faster than sigmoid.

**Comment by WangDeyu** [comment]
Well, does this modification affect performance?

**Comment by iamhankai** [comment]
The performance has no significant difference.

**Comment by WangDeyu** [comment]
OK, thanks!
