### ISSUE TITLE
Stride=1 cfg Kernel Sizes Never Used?

### ISSUE THREAD

**Issue by glenn-jocher** [iamhankai/ghostnet.pytorch#25]
The first column of the cfg are k kernel sizes:
https://github.com/iamhankai/ghostnet.pytorch/blob/8c601dffc35340da0ffa066c3f40c78ff0477e90/ghost_net.py#L175-L194

But unless `stride=2`, it appears GhostBottleneck() module does not use the cfg kernel size. Is this correct? If so setting these to 1 in the cfg may be more clear?

https://github.com/iamhankai/ghostnet.pytorch/blob/8c601dffc35340da0ffa066c3f40c78ff0477e90/ghost_net.py#L81-L108

**Comment by iamhankai** [comment]
You are right. The code is not clean... As said in https://github.com/huawei-noah/ghostnet/issues/12

**Comment by glenn-jocher** [comment]
@iamhankai ok got it, thank you! Was just checking to make sure I wasn't missing something.
