### ISSUE TITLE
kernet is kernel

### ISSUE THREAD

**Issue by freaad** [iamhankai/ghostnet.pytorch#29]
https://github.com/iamhankai/ghostnet.pytorch/blob/8c601dffc35340da0ffa066c3f40c78ff0477e90/ghost_net.py#L101
I think this is typo.

**Comment by iamhankai** [comment]
Thanks for your remind. I'll fix it soon. Duplicated to https://github.com/iamhankai/ghostnet.pytorch/issues/26
