### ISSUE TITLE
Can not run the sample

### ISSUE THREAD

**Issue by DYJ1111** [iamhankai/ghostnet.pytorch#30]
Hi, I use the sample code you provided, But it can not run. 

this is the error .

RuntimeError: Trying to create tensor with negative dimension -1: [80, 1, -1, -1]

**Comment by iamhankai** [comment]
Fixed: f3d8e5b4f182d4bd6958257f88efb97fb57e8083

**Comment by DYJ1111** [comment]
> Fixed: [f3d8e5b](https://github.com/iamhankai/ghostnet.pytorch/commit/f3d8e5b4f182d4bd6958257f88efb97fb57e8083)

thanks, I have test using your provided url. But it is also wrong, and at the 192 line, you lose a comma

**Comment by DYJ1111** [comment]
> Fixed: [f3d8e5b](https://github.com/iamhankai/ghostnet.pytorch/commit/f3d8e5b4f182d4bd6958257f88efb97fb57e8083)

and this is the error. 
RuntimeError: Trying to create tensor with negative dimension -1: [80, 1, -1, -1]

**Comment by iamhankai** [comment]
I test it and no error raises.

**Comment by DYJ1111** [comment]
> I test it and no error raises.

line 192 lose a comma. it doesn;t matter?

**Comment by DYJ1111** [comment]
> I test it and no error raises.



> I test it and no error raises.



> I test it and no error raises.

sorry, I know where i am wrong. Thank you
