### ISSUE TITLE
Params/ FLOPs counter

### ISSUE THREAD

**Issue by digantamisra98** [iamhankai/ghostnet.pytorch#31]
Hello
Could you please share the code you're using to obtain the parameters and FLOPs of your validated models as I'm getting conflicting numbers for ResNet-50 + Ghost using the FLOP/ Param counter provided here - https://github.com/sovrasov/flops-counter.pytorch

**Comment by iamhankai** [comment]
https://github.com/Lyken17/pytorch-OpCounter
