### ISSUE TITLE
如何应用到resnet模型？

### ISSUE THREAD

**Issue by splinter21** [iamhankai/ghostnet.pytorch#4]
1、论文中实验（表45）里的数据，是将哪些conv替换成ghost_conv?
Bottleneck里面，头尾1x1，中间3x3，是全部换了吗？

2、目前实验全部是为了压缩模型吗？有没有参数和计算量跟baseline一样（忽略ghost里的group-conv），得出结论，应用了ghost_conv能提点的实验？

**Comment by iamhankai** [comment]
1. 所有conv换成ghost_conv，第一层参数量计算量很小，可以不换。
2. 没有试过，不过我认为可以提点。
