### ISSUE TITLE
pretrained pth model for pytorch

### ISSUE THREAD

**Issue by dragen1860** [iamhankai/ghostnet.pytorch#5]
Dear author:
  Thanks for your timely open source implementation. 
   It would be grateful if you can publish some pretrained pth on ImageNet dataset. Thank you.

**Comment by iamhankai** [comment]
Currently, the pretrained model of TF version is available: https://github.com/huawei-noah/ghostnet

**Comment by Havenx707** [comment]
> Currently, the pretrained model of TF version is available: https://github.com/huawei-noah/ghostnet

Will you publish the pretrained model of pytorch version? @iamhankai

**Comment by iamhankai** [comment]
> Will you publish the pretrained model of pytorch version? @iamhankai

No exact date now. You can refer to https://github.com/iamhankai/ghostnet.pytorch/issues/3 for training hyperparameters.

**Comment by iamhankai** [comment]
Thanks to @d-li14. He has provided pretrained model at https://github.com/d-li14/ghostnet.pytorch
