### ISSUE TITLE
cheap_opt is liner in paper, why relu?

### ISSUE THREAD

**Issue by zhaowenlovehome** [iamhankai/ghostnet.pytorch#9]
cheap_opt is liner in paper, why relu?

**Comment by iamhankai** [comment]
`relu` can be moved behind the `concat`.

**Comment by zhaowenlovehome** [comment]
sorry,I just find out that the source code of paper is the same as you

**Comment by lmomoy** [comment]
sorry, so it is more accurate to move it behind the concat?

**Comment by iamhankai** [comment]
@lmomoy I think behind or before is equivalent.
